# These print messages to the console:
enable_langchain_debug_mode: False
enable_langchain_verbose_mode: False

logging:
  level: DEBUG
  verbose: False
  file: output.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

root_folder: D:\Temp\alfred_dump

models:
  default_model:
    name: MistralInstruct
    module: alfred_ai_backend.models.llama_cpp_local.mistral_instruct.MistralInstruct
  llama_cpp_local.mistral_instruct:
    name: MistralInstruct
    module: alfred_ai_backend.models.llama_cpp_local.mistral_instruct.MistralInstruct
  openai_api.chat_gpt:
    name: ChatGpt
    module: alfred_ai_backend.models.openai_api.chat_gpt.ChatGpt
  anthropic.claude:
    name: Claude
    module: alfred_ai_backend.models.anthropic.claude.Claude
